/**
 * Copyright 2016 Afero, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import Foundation

// A list of swift, java, kotlin reserved words. Sango will emit a compiler error if these are used
// as a class name, value name, or variable name

let reservedWords = [
    "abstract",
    "array",
    "as",
    "assert",
    "associativity",
    "bool",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "convenience",
    "default",
    "deinit",
    "dictionary",
    "didset",
    "do",
    "double",
    "dynamic",
    "else",
    "enum",
    "errortype",
    "extends",
    "extension",
    "fallthrough",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "fun",
    "func",
    "get",
    "goto",
    "guard",
    "if",
    "implements",
    "import",
    "in",
    "indirect",
    "infix",
    "init",
    "inout",
    "instanceof",
    "int",
    "interface",
    "internal",
    "is",
    "lazy",
    "left",
    "let",
    "long",
    "mutating",
    "native",
    "new",
    "nil",
    "none",
    "nonmutating",
    "null",
    "object",
    "operator",
    "optional",
    "override",
    "package",
    "postfix",
    "precedence",
    "prefix",
    "private",
    "protected",
    "protocol",
    "public",
    "repeat",
    "required",
    "return",
    "right",
    "self",
    "set",
    "short",
    "static",
    "strictfp",
    "string",
    "struct",
    "subscript",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "tuple",
    "type",
    "typealias",
    "typeof",
    "unicodescalar",
    "unowned",
    "val",
    "var",
    "void",
    "volatile",
    "weak",
    "when",
    "where",
    "while",
    "willset"
]

