//
//  Reserved.swift
//  Sango
//
//  Created by Steve Hales on 12/21/16.
//  Copyright © 2016 Afero, Inc. All rights reserved.
//

import Foundation

// A list of swift and java reserved words. Sango will emit a compiler error if these are used
// as a class name, value name, or variable name

let reservedWords = [
    "abstract",
    "array",
    "assert",
    "associativity",
    "bool",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "convenience",
    "default",
    "deinit",
    "dictionary",
    "didset",
    "do",
    "double",
    "dynamic",
    "else",
    "enum",
    "errortype",
    "extends",
    "extension",
    "fallthrough",
    "false",
    "final",
    "finally",
    "float",
    "for",
    "func",
    "get",
    "goto",
    "guard",
    "if",
    "implements",
    "import",
    "in",
    "indirect",
    "infix",
    "init",
    "inout",
    "instanceof",
    "int",
    "interface",
    "internal",
    "lazy",
    "left",
    "let",
    "long",
    "mutating",
    "native",
    "new",
    "nil",
    "none",
    "nonmutating",
    "null",
    "operator",
    "optional",
    "override",
    "package",
    "postfix",
    "precedence",
    "prefix",
    "private",
    "protected",
    "protocol",
    "public",
    "repeat",
    "required",
    "return",
    "right",
    "self",
    "set",
    "short",
    "static",
    "strictfp",
    "string",
    "struct",
    "subscript",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "tuple",
    "type",
    "unicodescalar",
    "unowned",
    "var",
    "void",
    "volatile",
    "weak",
    "where",
    "while",
    "willset"
]

